part of 'resource.dart';

class ColorResources {
  final Color primaryColor = const Color.fromARGB(255, 0, 101, 200);
  final Color textFieldSignInSignUpColor = Colors.black;
  final Color textFieldSignInSignUpIconColor = Colors.black;
  final Color loginScreenTitle = Colors.black;
  final Color loginScreenTextButton = const Color.fromARGB(255, 0, 101, 200);
  final Color loginScreenSubmitButton = const Color.fromARGB(255, 0, 101, 200);
  final Color bgFloatingActionButton = const Color.fromARGB(255, 0, 101, 200);
  final Color loginScreenSubmitButtonText = Colors.white;
  final Color loginScreenCircularIndicator = Colors.white;
  final Color selectionHandleColor = Colors.black;
  final Color appBar = Colors.white;
  final Color appBarIconTextColor = Colors.black;
  final Color popUpMenuIconColor = Colors.black;
  final Color shimmerBase = Colors.grey.shade400;
  final Color shimmerHighlight = Colors.grey.shade100;
  final Color sendMessageIcon = Colors.white;
  final Color sendMessageTextField = Colors.grey.shade200;
  final Color chatBubbleYourSideBG = Colors.grey.shade300;
  final Color chatBubbleBorder = Colors.black;
  final Color chatBubbleYourSideText = Colors.black;
  final Color chatBubbleOtherSideText = Colors.white;
  final Color chatBubbleSenderName = Colors.red;
  final Color statusOnlineColor = Colors.green;
  final Color statusOfflineColor = Colors.grey.shade400;
  final Color dividerColor = Colors.grey.shade400;
  final Color videoPlayIconText = Colors.white;
  final Color videoPlayContainer = const Color.fromRGBO(0, 0, 0, 0.5);
  final Color chatScreenDate = Colors.grey;
  final Color uploadImageSuccessButton = Colors.green;
  final Color textFieldIcon = Colors.black;
  final Color registrationImageRemoveIcon = Colors.red;
  final Color registrationImageBg = Colors.grey;
  final Color otpVerifyFieldWhenUnSelected = Colors.grey;
  final Color bgOfAllScreen = Colors.white;
  final Color chatScreenTextFieldBorder = Colors.grey;
  final Color createGroupButtonBg = Colors.grey;
  final Color createGroupButtonIcon = Colors.black;
  final Color exitGroupButton = Colors.red;
  final Color bottomNavBarUnSelectedItem = Colors.grey;
  final Color uploadStatusButtonIcon = Colors.white;
  final Color uploadStatusButtonBg = Colors.grey;
}
